/**
 * Tokori desktop IPC client. Talks to the local HTTP bridge the Tokori
 * desktop app exposes on 127.0.0.1:53210. Bearer-token auth; the token
 * is generated by the desktop app on first launch and shown in its
 * Settings → Local API panel.
 *
 * Today's surface (v0.1):
 *   GET  /v1/health
 *   GET  /v1/remote/info
 *   GET  /v1/workspaces
 *   GET  /v1/workspaces/:id/vocab
 *   POST /v1/workspaces/:id/vocab
 *   GET  /v1/dict/search
 *
 * Library / reader-doc create are NOT exposed by the local API yet —
 * the cloud has them, the desktop doesn't. The extension's
 * "Import to Tokori desktop" actions check this and surface a clear
 * "needs Tokori v0.X.Y, or use Cloud target" message when the
 * endpoint is missing.
 */

import { diacriticPinyin } from './dictionaries/cedict';
import type { LanguageCode } from './languages';

export class LocalApiError extends Error {
  constructor(
    public status: number,
    message: string,
  ) {
    super(message);
    this.name = 'LocalApiError';
  }
}

function headers(token: string | null, extra?: HeadersInit): HeadersInit {
  const h = new Headers(extra);
  if (token) h.set('authorization', `Bearer ${token}`);
  if (!h.has('content-type')) h.set('content-type', 'application/json');
  return h;
}

async function expect<T>(res: Response): Promise<T> {
  if (!res.ok) {
    let msg = `HTTP ${res.status}`;
    try {
      const body = (await res.json()) as { error?: { message?: string } };
      if (body?.error?.message) msg = body.error.message;
    } catch {}
    throw new LocalApiError(res.status, msg);
  }
  return res.json() as Promise<T>;
}

export async function ping(baseUrl: string): Promise<boolean> {
  try {
    const r = await fetch(`${baseUrl}/v1/health`, { signal: AbortSignal.timeout(1500) });
    return r.ok;
  } catch {
    return false;
  }
}

/** Ask the desktop app for a fresh pairing token. The desktop pops a
 *  native confirmation dialog and, on user approval, returns a bearer
 *  token the extension can store. Returns null if the user declined
 *  or the desktop refused (older version without /v1/pair). */
export async function requestPairing(
  baseUrl: string,
): Promise<{ token: string; deviceName?: string } | null> {
  try {
    const r = await fetch(`${baseUrl}/v1/pair/request`, {
      method: 'POST',
      headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ client: 'tokori-companion-extension' }),
      signal: AbortSignal.timeout(60_000),
    });
    if (!r.ok) return null;
    const data = (await r.json()) as { token?: string; deviceName?: string };
    return data.token ? { token: data.token, deviceName: data.deviceName } : null;
  } catch {
    return null;
  }
}

export interface LocalWorkspace {
  id: number;
  target_lang: LanguageCode;
  native_lang: string;
  name: string;
}

export async function listWorkspaces(baseUrl: string, token: string): Promise<LocalWorkspace[]> {
  const res = await fetch(`${baseUrl}/v1/workspaces`, { headers: headers(token) });
  const data = await expect<{ data: LocalWorkspace[] }>(res);
  return data.data;
}

export interface VocabRow {
  id: number;
  word: string;
  reading?: string | null;
  gloss?: string | null;
  status: string;
  added_at: number;
}

/** List vocab entries for a workspace. Used by the content script to
 *  highlight already-known words inside captions / pages. The desktop
 *  caps `limit` at 500 server-side, so very large vocab sets will be
 *  capped to the most-recent 500 by default. */
export async function listVocab(
  baseUrl: string,
  token: string,
  workspaceId: number,
  opts?: { status?: string; limit?: number },
): Promise<VocabRow[]> {
  const url = new URL(`${baseUrl}/v1/workspaces/${workspaceId}/vocab`);
  if (opts?.status) url.searchParams.set('status', opts.status);
  url.searchParams.set('limit', String(opts?.limit ?? 500));
  const res = await fetch(url.toString(), { headers: headers(token) });
  const data = await expect<{ data: VocabRow[] }>(res);
  return data.data;
}

export interface CreateVocabInput {
  workspaceId: number;
  word: string;
  reading?: string;
  /** Maps to the desktop's `gloss` column. */
  definition?: string;
  sentence?: string;
  translation?: string;
  source_url?: string;
  tags?: string[];

  // ── Mining fields ──────────────────────────────────────────────
  //
  // All optional. Desktop versions prior to the mining release will
  // silently drop unknown keys — the route is `serde(default)` on the
  // Rust side — so the request is safe to send to any paired desktop.
  //
  /** `'vocab'` (default) — sentence/picture/clip attach to a vocab
   *  entry whose `word` is the studied surface form.
   *  `'sentence'` — store the whole sentence as the record's `word`
   *  with kind='sentence'. The desktop's study UI renders this as a
   *  sentence card (cloze hidden on front, revealed on back). */
  kind?: 'vocab' | 'sentence';
  /** Sentence with the studied word cloze-marked, e.g.
   *  `"I went to the {{c1::store}} yesterday"`. Stored in the desktop's
   *  `front_extra` column (same convention the desktop UI uses for its
   *  built-in cloze field). */
  front_extra?: string;
  /** Free-form notes / mnemonics. Maps to `card_notes` column. */
  card_notes?: string;
  /** Captured screenshot as a base64 data URL — same format the
   *  desktop UI writes via `updateVocabFields(imageData)`. */
  image_data?: string;
  /** Captured audio (typically the mined clip's bytes). BARE base64 —
   *  no `data:` prefix — the desktop decodes it straight into its
   *  `audio_data` BLOB column (unlike `image_data`, which stores a
   *  data URL verbatim). `audio_mime` carries the MIME so the desktop
   *  can serve it back. */
  audio_data?: string;
  audio_mime?: string;
  /** Captured short A/V clip as a base64 data URL. The desktop will
   *  decode + persist as a BLOB to avoid storage bloat. Requires the
   *  V7 desktop schema. */
  clip_data?: string;
  clip_mime?: string;
}

export async function createVocab(
  baseUrl: string,
  token: string,
  input: CreateVocabInput,
): Promise<{ id: number }> {
  const { workspaceId, ...body } = input;
  const res = await fetch(`${baseUrl}/v1/workspaces/${workspaceId}/vocab`, {
    method: 'POST',
    headers: headers(token),
    body: JSON.stringify(body),
  });
  return expect<{ id: number }>(res);
}

export interface DictHit {
  word: string;
  reading?: string;
  definitions: string[];
}

/** Raw row shape returned by `GET /v1/dict/search` on the desktop. The
 *  desktop's SQLite schema stores one row per dictionary entry, with
 *  `gloss` as a single string (typically slash- or semicolon-separated
 *  for CEDICT-style sources). Multiple rows can share the same `word`
 *  when there are alternate parts-of-speech / register variants. */
interface DesktopDictRow {
  word: string;
  alt_word?: string | null;
  reading?: string | null;
  gloss: string;
}

export async function dictSearch(
  baseUrl: string,
  token: string,
  lang: LanguageCode,
  q: string,
): Promise<DictHit[]> {
  const url = new URL(`${baseUrl}/v1/dict/search`);
  url.searchParams.set('lang', lang);
  url.searchParams.set('q', q);
  const res = await fetch(url.toString(), { headers: headers(token) });
  const data = await expect<{ data: DesktopDictRow[] }>(res);
  return reshapeDesktopRows(data.data || []);
}

/** Segment text into words via the desktop's jieba-backed tokenizer. Only
 *  Chinese gets real segmentation today; other languages get a single-
 *  element echo and the caller is expected to fall back to
 *  Intl.Segmenter. Short timeout because cues rotate every few seconds. */
export async function tokenize(
  baseUrl: string,
  token: string,
  lang: LanguageCode,
  text: string,
): Promise<string[]> {
  const res = await fetch(`${baseUrl}/v1/tokenize`, {
    method: 'POST',
    headers: headers(token),
    body: JSON.stringify({ lang, text }),
    signal: AbortSignal.timeout(2500),
  });
  const data = await expect<{ tokens: string[] }>(res);
  return data.tokens || [];
}

/** Collapse desktop rows ({word, gloss}) into the extension's
 *  `DictHit` shape ({word, reading?, definitions[]}). Multiple rows
 *  sharing the same word + reading combine into one hit with multiple
 *  definitions. Glosses are split on `/`, `;`, or ` | ` to recover
 *  the sub-definitions CEDICT / JMdict packs typically encode. */
function reshapeDesktopRows(rows: DesktopDictRow[]): DictHit[] {
  const out: DictHit[] = [];
  const byKey = new Map<string, DictHit>();
  for (const r of rows) {
    if (!r.word) continue;
    // CC-CEDICT stores pinyin with tone digits ("yu3"); JMdict + Yomitan
    // packs store kana / IPA directly. Convert digits → diacritics so the
    // popup never has to know which dict it came from.
    const rawReading = r.reading || undefined;
    const reading = rawReading && /\d/.test(rawReading) ? diacriticPinyin(rawReading) : rawReading;
    const key = `${r.word}${reading || ''}`;
    const defs = splitGloss(r.gloss || '');
    let hit = byKey.get(key);
    if (!hit) {
      hit = { word: r.word, reading, definitions: [] };
      byKey.set(key, hit);
      out.push(hit);
    }
    for (const d of defs) {
      if (d && !hit.definitions.includes(d)) hit.definitions.push(d);
    }
  }
  // Keep entries even when no definitions parsed — the user at least
  // sees that the desktop *did* have the word, with an explicit
  // placeholder so the popup doesn't render an empty bullet list.
  for (const h of out) {
    if (h.definitions.length === 0) h.definitions.push('(no definition stored)');
  }
  return out;
}

function splitGloss(s: string): string[] {
  return s
    .split(/\s*\/\s*|\s*;\s*|\s+\|\s+/)
    .map((x) => x.trim())
    .filter(Boolean);
}

export type VocabStatus = 'new' | 'learning' | 'review' | 'mastered';

/** Upsert a word's SRS status on the desktop (`POST /v1/vocab/status`).
 *  Creates the vocab row when the word isn't in the workspace yet, so
 *  a learner can mark an unseen word straight from a popup. */
export async function setVocabStatus(
  baseUrl: string,
  token: string,
  input: {
    workspaceId: number;
    word: string;
    reading?: string;
    gloss?: string;
    status: VocabStatus;
  },
): Promise<{ id: number; status: VocabStatus; existed: boolean }> {
  const res = await fetch(`${baseUrl}/v1/vocab/status`, {
    method: 'POST',
    headers: headers(token),
    body: JSON.stringify({
      workspace_id: input.workspaceId,
      word: input.word,
      reading: input.reading,
      gloss: input.gloss,
      status: input.status,
    }),
  });
  return expect<{ id: number; status: VocabStatus; existed: boolean }>(res);
}

// ── Collections ("+ List" in the word popup) ──────────────────────

/** Raw desktop collection row (snake_case, SQLite booleans as 0/1). */
interface DesktopCollectionRow {
  id: number;
  workspace_id: number;
  name: string;
  description?: string | null;
  is_default: number;
  source: string;
}

export interface LocalCollection {
  id: number;
  name: string;
  isDefault: boolean;
}

export async function listCollections(
  baseUrl: string,
  token: string,
  workspaceId: number,
): Promise<LocalCollection[]> {
  const res = await fetch(`${baseUrl}/v1/workspaces/${workspaceId}/collections`, {
    headers: headers(token),
  });
  const data = await expect<{ data: DesktopCollectionRow[] }>(res);
  return (data.data || []).map((r) => ({
    id: r.id,
    name: r.name,
    isDefault: !!r.is_default,
  }));
}

export async function createCollection(
  baseUrl: string,
  token: string,
  workspaceId: number,
  name: string,
): Promise<LocalCollection> {
  const res = await fetch(`${baseUrl}/v1/workspaces/${workspaceId}/collections`, {
    method: 'POST',
    headers: headers(token),
    body: JSON.stringify({ name }),
  });
  const row = await expect<DesktopCollectionRow>(res);
  return { id: row.id, name: row.name, isDefault: !!row.is_default };
}

/** Upsert + link words into a collection (`POST /v1/collections/:id/words`).
 *  The desktop resolves the workspace from the collection itself. */
export async function addWordsToCollection(
  baseUrl: string,
  token: string,
  collectionId: number,
  words: Array<{ word: string; reading?: string; gloss?: string }>,
): Promise<{ added: number; skipped: number; existed: number }> {
  const res = await fetch(`${baseUrl}/v1/collections/${collectionId}/words`, {
    method: 'POST',
    headers: headers(token),
    body: JSON.stringify({ words }),
  });
  return expect<{ added: number; skipped: number; existed: number }>(res);
}

/** One-shot chat completion through the desktop's active AI provider
 *  (`POST /v1/chat/stream`, SSE). We read the stream to completion and
 *  return the final text — used by "Generate definition" so the
 *  extension can piggy-back on the user's desktop provider setup. */
export async function chatOnce(
  baseUrl: string,
  token: string,
  messages: Array<{ role: 'system' | 'user' | 'assistant'; content: string }>,
): Promise<string> {
  const res = await fetch(`${baseUrl}/v1/chat/stream`, {
    method: 'POST',
    headers: headers(token),
    body: JSON.stringify({ messages }),
    signal: AbortSignal.timeout(60_000),
  });
  if (!res.ok) {
    let msg = `HTTP ${res.status}`;
    try {
      const body = (await res.json()) as { error?: { message?: string } };
      if (body?.error?.message) msg = body.error.message;
    } catch {}
    throw new LocalApiError(res.status, msg);
  }
  // SSE frames: {type:"token",delta} … {type:"done",content} |
  // {type:"error",message}. Prefer the final `done` content; fall back
  // to concatenated deltas if the stream was cut before it arrived.
  const raw = await res.text();
  let tokens = '';
  for (const line of raw.split('\n')) {
    const payload = line.startsWith('data:') ? line.slice(5).trim() : null;
    if (!payload) continue;
    try {
      const ev = JSON.parse(payload) as {
        type: 'token' | 'done' | 'error';
        delta?: string;
        content?: string;
        message?: string;
      };
      if (ev.type === 'done' && ev.content) return ev.content;
      if (ev.type === 'error') throw new LocalApiError(502, ev.message || 'Desktop AI failed.');
      if (ev.type === 'token') tokens += ev.delta || '';
    } catch (e) {
      if (e instanceof LocalApiError) throw e;
      /* keep-alive frame */
    }
  }
  if (!tokens.trim()) throw new LocalApiError(502, 'Desktop AI returned an empty response.');
  return tokens;
}

/** LLM-backed translation through the desktop's active AI provider
 *  (`POST /v1/translate`). The desktop's richer engine registry
 *  (DeepL etc.) is frontend-only, so this is the one HTTP-reachable
 *  translate surface. */
export async function translate(
  baseUrl: string,
  token: string,
  input: { text: string; source?: string; target?: string },
): Promise<{ translation: string }> {
  const res = await fetch(`${baseUrl}/v1/translate`, {
    method: 'POST',
    headers: headers(token),
    body: JSON.stringify(input),
    signal: AbortSignal.timeout(30_000),
  });
  return expect<{ translation: string }>(res);
}

export interface AiExplainResult {
  explanation: string;
  provider?: string;
  model?: string;
}

/** Ask the desktop app's AI proxy to explain a sentence. The desktop
 *  uses whichever provider the user has configured there (Claude, GPT,
 *  local Ollama, …), so the extension can piggy-back on the user's
 *  existing setup instead of asking for separate keys. */
export async function aiExplain(
  baseUrl: string,
  token: string,
  input: { text: string; lang: LanguageCode },
): Promise<AiExplainResult> {
  const res = await fetch(`${baseUrl}/v1/ai/explain`, {
    method: 'POST',
    headers: headers(token),
    body: JSON.stringify(input),
    signal: AbortSignal.timeout(30_000),
  });
  return expect<AiExplainResult>(res);
}
